server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cnode?useSSL=true
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        security: DEBUG