server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cnode?useSSL=true
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        security: DEBUG
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)
  tokenHead: 'Bearer ' #JWT负载中拿到开头

secure:
  ignored:
      #安全路径白名单
      postUrls:
        - /register
        - /login
      getUrls:
        - /user/**
        - /topics
        - /topic/{topicId:[0-9]+}
        - /topic_collect/{loginname:\w+}